/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stronans_pilgrim_data_model_StaticData */

#ifndef _Included_com_stronans_pilgrim_data_model_StaticData
#define _Included_com_stronans_pilgrim_data_model_StaticData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stronans_pilgrim_data_model_StaticData
 * Method:    hasChildFolders
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_stronans_pilgrim_data_model_StaticData_hasChildFolders
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
